# NumPy

## Array input and output

Let's start by creating an array **from data in a file**:

In [1]:
import numpy as np

a = np.loadtxt('../data/numbers.txt')
print(a)

[ 1.630000e+00 -3.278000e+01 -4.100000e+00  2.530700e+01  8.000000e+00
  3.133333e+01  7.804592e+02 -4.223430e+02  8.761200e+01  9.287000e+02
 -1.870000e+02  1.153040e+03  4.200000e+00  9.320000e-01  5.650000e+00
 -8.205900e+03 -2.749655e+03  5.912000e+00  2.347105e+03  3.920000e+01
  6.150000e+01]


Notice that the default output uses **scientific notation** and has lots of digits after the floating point! We can change this as follows - `precision` is the number digits after the floating point and `suppress` turns off scientific notation.  

In [2]:
# set precision and suppress scientific notation
np.set_printoptions(precision=2, suppress=True)
print(a)

[    1.63   -32.78    -4.1     25.31     8.      31.33   780.46  -422.34
    87.61   928.7   -187.    1153.04     4.2      0.93     5.65 -8205.9
 -2749.66     5.91  2347.11    39.2     61.5 ]


Note, however, that `set_printoptions` applies to NumPy arrays, not the output from from array methods, such as this one:

In [3]:
print(a.sum())

-6121.197470000002


## Working with arrays

Let's start by returning to the issue of precision in the previous example. How much "lost information" is there when we **round numbers** to a small number of decimal places? Here's one way of thinking about it &mdash; feel free to modify the parameters here:

In [76]:
precise = np.random.rand(1000) 
print('Original:', precise[:10])
rounded = np.round(precise, decimals=0)
print('Rounded:', rounded[:10])

diff = precise - rounded
print('\nTotal difference:', diff.sum())
print('Maximum difference:', diff.max())
print('Mean difference:', diff.mean())

Original: [0.80597832 0.77280756 0.95467866 0.94747145 0.83215701 0.07043579
 0.26446075 0.59185772 0.6610026  0.76007534]
Rounded: [1. 1. 1. 1. 1. 0. 0. 1. 1. 1.]

Total difference: -1.7514627964933571
Maximum difference: 0.4996327372254583
Mean difference: -0.001751462796493357


Here is an example of **virtual coin tossing**. See if you can work out what's going on:

In [101]:
import numpy as np

rng = np.random.default_rng() # put a value here after you read the text below this cell
print(rng)

size = 1000
upper_bound = 9
a = rng.integers(upper_bound, size=size) # array.integers
b = rng.integers(upper_bound, size=size)

c = a == b
print(c.sum(), '/', size) # c is a True False array, checking if the value of a is the same as b each time (1 = heads, 2 = tails)
print(a[:15])
print(b[:10])
print(c[:10])

Generator(PCG64)
115 / 1000
[2 5 1 3 8 5 5 6 3 3 5 5 2 6 5]
[6 7 4 1 8 1 2 4 8 2]
[False False False False  True False False False False False]


what happens if you run the code above multiple time ? What happens then, if you set a default value for the random number genrator and run the code multiple time?

## Working with matrices

Here I've used the `np.arange()` (array range) in combination with the `reshape()` method to create a populated matrix. I then manipulate the matrix by applying various operations: transposing, flipping, flattening and slicing. 

In [79]:
A = np.arange(24).reshape((4, 6))
print('Original:')
print(A)

# Transposition
print('\nTransposed:')
B = A.transpose()
print(B)
print('Shape:', B.shape)

# Flipping
print('\nFlipped horizontally and vertically:')
print(np.flip(A))
print('\nFlipped vertically:')
print(np.flip(A, 0))
print('\nFlipped horizontally:')
print(np.flip(A, 1))

# Flattening
print('\nFlattened:')
print(A.flatten())
print('\nFlattened and reversed:')
print(np.flip(A.flatten()))

# Slicing
C = A[1:4, 1:3]
print('\nSliced:')
print(C)

Original:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

Transposed:
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]
Shape: (6, 4)

Flipped horizontally and vertically:
[[23 22 21 20 19 18]
 [17 16 15 14 13 12]
 [11 10  9  8  7  6]
 [ 5  4  3  2  1  0]]

Flipped vertically:
[[18 19 20 21 22 23]
 [12 13 14 15 16 17]
 [ 6  7  8  9 10 11]
 [ 0  1  2  3  4  5]]

Flipped horizontally:
[[ 5  4  3  2  1  0]
 [11 10  9  8  7  6]
 [17 16 15 14 13 12]
 [23 22 21 20 19 18]]

Flattened:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

Flattened and reversed:
[23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]

Sliced:
[[ 7  8]
 [13 14]
 [19 20]]
